sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env:
        - CS_CHECK=true
        - TEST_COVERAGE=true
    - php: 7.2
    - php: 7.3

install:
  - travis_retry composer install --no-interaction

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --disallow-test-output --coverage-clover ./clover.xml ; else ./vendor/bin/phpunit --disallow-test-output ; fi
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml ; fi

notifications:
  email: false